; Saved by valkyrie-mom-mcp 2.5.2

[QItemSpade]
itemname=ItemCommonShovel
starting=True

[QItemDarkLantern]
itemname=ItemCommonKeroseneLantern
starting=True

[QItemMedicalBag]
itemname=ItemCommonBandages
starting=False

[QItemMedicalText]
itemname=ItemCommonMedicalTextbook
starting=False
inspect=EventFormulaStudy
