; Saved by valkyrie-mom-mcp 2.3.1

[Quest]
format=21
type=MoM
hidden=false
defaultlanguage=English
defaultmusicon=true
difficulty=0.5
lengthmin=60
lengthmax=90
image=img/Intro.jpg
minhero=1
maxhero=4

[QuestText]
Localization.English.txt

[QuestData]
events.ini
tiles.ini
tokens.ini
spawns.ini
items.ini
ui.ini
other.ini
