; Saved by valkyrie-mom-mcp 2.3.1

[CustomMonsterSpecimenThrall]
base=MonsterThrall
image=img/Specimen.jpg
imageplace=img/Specimen.jpg
activation=EventSpecimenActivation
health=4
healthperhero=2
evadeevent=EventSpecimenEvade
horrorevent=EventSpecimenHorror
horror=3
awareness=2

[CustomMonsterSpecimenHybrid]
base=MonsterDeepOneHybrid
image=img/Specimen.jpg
imageplace=img/Specimen.jpg
activation=EventSpecimenActivation
health=4
healthperhero=2
evadeevent=EventSpecimenEvade
horrorevent=EventSpecimenHorror
horror=3
awareness=2

[SpawnSpecimenThrall]
xposition=23.5
yposition=-2
vartests=VarOperation:#BtT,==,1
buttons=1
event1=
monster=CustomMonsterSpecimenThrall
unique=true
uniquehealth=0
uniquehealthhero=0

[SpawnSpecimenHybrid]
xposition=23.5
yposition=-2
buttons=1
event1=
monster=CustomMonsterSpecimenHybrid
unique=true
uniquehealth=0
uniquehealthhero=0
