; Saved by valkyrie-mom-mcp 2.3.1

[TilePottersField]
xposition=0
yposition=0
side=TileSideToolShed

[TileLane]
xposition=7
yposition=0
side=TileSideYard2
rotation=180

[TileFarmhouse]
xposition=20
yposition=0
side=TileSideDiningRoom

[TileCellar]
xposition=27
yposition=0
side=TileSideBasement
