; Saved by valkyrie-mom-mcp 2.5.2

[UIIntroBG]
xposition=0
yposition=0
display=false
buttons=0
image=ImageCutsceneBG
size=1
vunits=True

[UIIntroPicture]
xposition=-0.28
yposition=0
display=false
buttons=0
image=img/Intro.jpg
size=0.8
vunits=True

[UIIntroText]
xposition=0.47
yposition=0.015
display=false
buttons=0
image=
size=0.69
textsize=0.7
richText=True
textAlignment=TOP
vunits=True
textaspect=0.725

[UIIntroButtonFrame]
xposition=0.47
yposition=0
display=false
buttons=0
image=ImageInvestigatorSelectTitle
size=0.078
vunits=True
valign=bottom

[UIIntroButton]
xposition=0.47
yposition=0
display=false
buttons=1
event1=EventProloguePlan
image=
size=0.078
textcolor=black
richText=True
vunits=True
textaspect=7
valign=bottom

[UIDeathNotice]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/DeathNotice.jpg
size=0.62
vunits=True

[UILaboratory]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/Laboratory.jpg
size=0.58
vunits=True

[UIEscape]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/Escape.jpg
size=0.58
vunits=True

[UIFormula]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/Formula.jpg
size=0.66
vunits=True

[UIIntroFrame]
xposition=-0.28
yposition=0
display=false
buttons=0
image=ImageCutsceneFrame
size=0.88
vunits=True

[UIIntroTopper]
xposition=0.47
yposition=-0.364
display=false
buttons=0
image=ImageCutsceneTextTopper
size=0.031
vunits=True
