; Saved by valkyrie-mom-mcp 2.3.1

[UIIntroBG]
xposition=-0.06
yposition=0
display=false
buttons=0
image=ImageCutsceneBG
size=1
vunits=True

[UIIntroPicture]
xposition=-0.45
yposition=0
display=false
buttons=0
image=img/Intro.jpg
size=0.9
vunits=True

[UIIntroText]
xposition=0.35
yposition=0.05
display=false
buttons=0
image=
size=0.95
textsize=0.75
richText=True
textAlignment=TOP
vunits=True
textaspect=0.95

[UIIntroButtonFrame]
xposition=0.4
yposition=0
display=false
buttons=0
image=ImageInvestigatorSelectTitle
size=0.1
vunits=True
valign=bottom

[UIIntroButton]
xposition=0.4
yposition=0.04
display=false
buttons=1
event1=EventProloguePlan
image=
size=1
textcolor=black
richText=True
textAlignment=BOTTOM
vunits=True
valign=bottom

[UIDeathNotice]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/DeathNotice.jpg
size=0.62
vunits=True

[UILaboratory]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/Laboratory.jpg
size=0.58
vunits=True

[UIEscape]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/Escape.jpg
size=0.58
vunits=True

[UIFormula]
xposition=0
yposition=0.13
display=false
buttons=0
image=img/Formula.jpg
size=0.66
vunits=True
